from typing import Any, Protocol, Tuple

class Backend(Protocol):
    def array(self, data: Any) -> Any: ...
    def matmul(self, a: Any, b: Any) -> Any: ...
    def add(self, a: Any, b: Any) -> Any: ...
    def zeros(self, shape: Tuple[int, ...]) -> Any: ...
    def random_normal(self, shape: Tuple[int, ...], scale: float = 1.0) -> Any: ...
